# Generated by Django 4.2.7 on 2023-11-25 21:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0005_remove_profile_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachinePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('machine_name', models.CharField(max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 12, 25, 21, 3, 22, 371570, tzinfo=datetime.timezone.utc))),
                ('remaining_days', models.IntegerField(default=30)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recommending_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
