# Generated by Django 4.2.7 on 2023-11-26 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0007_remove_machinepurchase_recommending_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinepurchase',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 21, 21, 0, 745376, tzinfo=datetime.timezone.utc)),
        ),
    ]
