# Generated by Django 4.2.8 on 2023-12-11 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0008_alter_machinepurchase_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinepurchase',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 10, 33, 3, 986814, tzinfo=datetime.timezone.utc)),
        ),
    ]
