# Generated by Django 4.2.7 on 2023-11-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_rev',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
