# Generated by Django 4.2.7 on 2023-11-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_profile_total_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_rev',
        ),
    ]
