# Generated by Django 4.2.7 on 2023-11-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankInfo',
        ),
    ]
