# Generated by Django 4.2.7 on 2023-11-14 11:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0002_alter_buttonclick_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buttonclick',
            unique_together={('user', 'machine_name')},
        ),
    ]
