# Generated by Django 4.2.7 on 2023-11-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_buttonclick_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buttonclick',
            unique_together=set(),
        ),
    ]
