# Generated by Django 4.2.7 on 2023-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_alter_buttonclick_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonclick',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
