# Generated by Django 4.2.7 on 2023-11-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_buttonclick_total_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonclick',
            name='total_income',
        ),
    ]
