# Generated by Django 4.2.7 on 2023-11-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0009_remove_buttonclick_total_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonclick',
            name='ref_income',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
